### ISSUE TITLE
Error after installation (xunit 2.4.3 ?)

### ISSUE THREAD

**Issue by MuddyWally** [yowko/xUnit.net.TestGenerator2022#1]
After installation of the extension and using it on the first project, NuGet shows an error, that xUnit 2.4.3 is not available, and I think it's right :-)

In `xUnit.net.TestGenerator.xUnitSolutionManager` are two lines:
```
     this.EnsureNuGetReference(unitTestProject, "xunit", "2.4.3");
     this.EnsureNuGetReference(unitTestProject, "xunit.runner.visualstudio", "2.4.3");
```
The last stable version on [xunit.net](https://xunit.net/) is 2.4.1 and the last pre-release is 2.4.2-pre.19.
Is it possible, that there is no 2.4.3, yet?

After installation of the extension and using it on the first project, NuGet shows an error, that xUnit 2.4.3 is not available, and I think it's right :-)

In `xUnit.net.TestGenerator.xUnitSolutionManager` are two lines:
```
     this.EnsureNuGetReference(unitTestProject, "xunit", "2.4.3");
     this.EnsureNuGetReference(unitTestProject, "xunit.runner.visualstudio", "2.4.3");
```
The last stable version on [xunit.net](https://xunit.net/) is 2.4.1 and the last pre-release is 2.4.2-pre.19.
Is it possible, that there is no 2.4.3, yet?

谢谢！

**Comment by yowko** [comment]
Hi,
It's a workaround to use version 2.4.3. 
The strategy for VisualStudio to download NuGet has changed.
At first, set the version to `null` will use the latest stable version.
Then  `null` throws exceptions, I set a future version number to download to the latest version.

Now it changed again, I have uploaded a new version(1.1) to fix it.

Please reopen the issue, If the new version(1.1) is not workable.

**Comment by MuddyWally** [comment]
Thanks a lot for the clarification (and for the extension, of course :-) )!
